version: '3.8'
# docker-compose -f docker-compose.monitoring.yml up -d
# id grafana for spring 12900
# Prometheus server URL http://prometheus:9090
services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - deploy_app-network  # Corrected network name

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "4000:3000"  # Using port 4000 instead of 3000 to avoid conflicts
    networks:
      - deploy_app-network
volumes:
  grafana-data:

networks:
  deploy_app-network:
    external: true
