global:
  scrape_interval: 15s  # Set the scrape interval to 15 seconds

scrape_configs:
  - job_name: 'zyn1724063370856Ms1-v1'
    scheme: https  # Assuming HTTPS is required
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

    static_configs:
  - targets: ['zyn1724063370856Ms1-v1:8037']
    tls_config:
      insecure_skip_verify: true  # Only if you want to skip TLS verification
  - job_name: 'zyn1724063370856Ms2-v1'
    scheme: https  # Assuming HTTPS is required
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

    static_configs:
  - targets: ['zyn1724063370856Ms2-v1:8038']
    tls_config:
      insecure_skip_verify: true  # Only if you want to skip TLS verification

